version: '3'
services:
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  data_collection:
    build: ./microservices/data_collection
    depends_on:
      - kafka

  anomaly_detection:
    build: ./microservices/anomaly_detection
    depends_on:
      - kafka

  incident_detection:
    build: ./microservices/incident_detection
    depends_on:
      - kafka

  response_management:
    build: ./microservices/response_management
    depends_on:
      - kafka
